-- coagroup.sql


/* =============================================
 * CREATE TABLE act."coagroup"
 * ============================================*/
create table act."coagroup" (
	coagroup_id smallint generated by default as identity,
	constraint coagroup_pk primary key (coagroup_id)
);
comment on table act."coagroup" is '';	


-- =============================================
-- FIELD: coagroup_name text
-- =============================================
-- ADD coagroup_name
alter table act."coagroup" add coagroup_name text  ;
comment on column act."coagroup".coagroup_name is '';

-- MODIFY coagroup_name
alter table act."coagroup"
	alter column coagroup_name type text,
	ALTER COLUMN coagroup_name DROP DEFAULT,
	ALTER COLUMN coagroup_name DROP NOT NULL;
comment on column act."coagroup".coagroup_name is '';


-- =============================================
-- FIELD: coagroup_descr text
-- =============================================
-- ADD coagroup_descr
alter table act."coagroup" add coagroup_descr text  ;
comment on column act."coagroup".coagroup_descr is '';

-- MODIFY coagroup_descr
alter table act."coagroup"
	alter column coagroup_descr type text,
	ALTER COLUMN coagroup_descr DROP DEFAULT,
	ALTER COLUMN coagroup_descr DROP NOT NULL;
comment on column act."coagroup".coagroup_descr is '';


-- =============================================
-- FIELD: coagroup_isparent boolean
-- =============================================
-- ADD coagroup_isparent
alter table act."coagroup" add coagroup_isparent boolean not null default false;
comment on column act."coagroup".coagroup_isparent is '';

-- MODIFY coagroup_isparent
alter table act."coagroup"
	alter column coagroup_isparent type boolean,
	ALTER COLUMN coagroup_isparent SET DEFAULT false,
	ALTER COLUMN coagroup_isparent SET NOT NULL;
comment on column act."coagroup".coagroup_isparent is '';


-- =============================================
-- FIELD: coagroup_parent smallint
-- =============================================
-- ADD coagroup_parent
alter table act."coagroup" add coagroup_parent smallint  ;
comment on column act."coagroup".coagroup_parent is '';

-- MODIFY coagroup_parent
alter table act."coagroup"
	alter column coagroup_parent type smallint,
	ALTER COLUMN coagroup_parent DROP DEFAULT,
	ALTER COLUMN coagroup_parent DROP NOT NULL;
comment on column act."coagroup".coagroup_parent is '';


-- =============================================
-- FIELD: coagroup_pathid text
-- =============================================
-- ADD coagroup_pathid
alter table act."coagroup" add coagroup_pathid text  ;
comment on column act."coagroup".coagroup_pathid is '';

-- MODIFY coagroup_pathid
alter table act."coagroup"
	alter column coagroup_pathid type text,
	ALTER COLUMN coagroup_pathid DROP DEFAULT,
	ALTER COLUMN coagroup_pathid DROP NOT NULL;
comment on column act."coagroup".coagroup_pathid is '';


-- =============================================
-- FIELD: coagroup_path text
-- =============================================
-- ADD coagroup_path
alter table act."coagroup" add coagroup_path text  ;
comment on column act."coagroup".coagroup_path is '';

-- MODIFY coagroup_path
alter table act."coagroup"
	alter column coagroup_path type text,
	ALTER COLUMN coagroup_path DROP DEFAULT,
	ALTER COLUMN coagroup_path DROP NOT NULL;
comment on column act."coagroup".coagroup_path is '';


-- =============================================
-- FIELD: coagroup_level smallint
-- =============================================
-- ADD coagroup_level
alter table act."coagroup" add coagroup_level smallint not null default 0;
comment on column act."coagroup".coagroup_level is '';

-- MODIFY coagroup_level
alter table act."coagroup"
	alter column coagroup_level type smallint,
	ALTER COLUMN coagroup_level SET DEFAULT 0,
	ALTER COLUMN coagroup_level SET NOT NULL;
comment on column act."coagroup".coagroup_level is '';


-- =============================================
-- FIELD: _createby bigint
-- =============================================
-- ADD _createby
alter table act."coagroup" add _createby bigint not null ;
comment on column act."coagroup"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table act."coagroup"
	alter column _createby type bigint,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column act."coagroup"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table act."coagroup" add _createdate timestamp with time zone not null ;
comment on column act."coagroup"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table act."coagroup"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate DROP DEFAULT,
	ALTER COLUMN _createdate SET NOT NULL;
comment on column act."coagroup"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby bigint
-- =============================================
-- ADD _modifyby
alter table act."coagroup" add _modifyby bigint  ;
comment on column act."coagroup"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table act."coagroup"
	alter column _modifyby type bigint,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column act."coagroup"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table act."coagroup" add _modifydate timestamp with time zone  ;
comment on column act."coagroup"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table act."coagroup"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column act."coagroup"._modifydate is 'waktu terakhir record dimodifikasi';




-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Drop Existing Foreign Key Constraint 
ALTER TABLE act."coagroup" DROP CONSTRAINT fk$act$coagroup$coagroup_parent;


-- Add Foreign Key Constraint  
ALTER TABLE act."coagroup"
	ADD CONSTRAINT fk$act$coagroup$coagroup_parent
	FOREIGN KEY (coagroup_parent)
	REFERENCES act."coagroup"(coagroup_id);


-- Add As Index, drop dulu jika sudah ada
DROP INDEX IF EXISTS act.idx_fk$act$coagroup$coagroup_parent;
CREATE INDEX idx_fk$act$coagroup$coagroup_parent ON act."coagroup"(coagroup_parent);	

	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table act."coagroup"
	drop constraint uq$act$coagroup$coagroup_name;
	

-- Add unique index 
alter table  act."coagroup"
	add constraint uq$act$coagroup$coagroup_name unique (coagroup_parent, coagroup_name); 

