
CREATE TABLE act.jurnalsaldo (
	jurnalsaldo_id int8 GENERATED BY DEFAULT AS identity( INCREMENT BY 1 START 1) not null,
	jurnalsaldo_date date,
	
	periode_id int2 NULL,
	
	jurnal_doc varchar(30),
	jurnal_id int8 NULL,
	jurnal_date date DEFAULT now() NULL,
	jurnal_datedue date DEFAULT now() NULL,
	
	jurnaldetil_id int8 NOT NULL,
	jurnaldetil_descr text NULL,
	jurnaldetil_idr numeric(18, 2) DEFAULT 0 NOT NULL,
	jurnaldetil_value numeric(13, 2) DEFAULT 0 NOT NULL,

	curr_id int2 NULL,
	coa_id int4 NULL,
	unit_id int4 NULL,
	site_id int4 NULL,
	dept_id int4 NULL,
	partner_id int4 NULL,
	project_id int4 NULL,
	
	saldoawal_idr numeric(18, 2) DEFAULT 0 NOT NULL,
	saldoawal_value numeric(13, 2) DEFAULT 0 NOT NULL,

	CONSTRAINT jurnalsaldo_pk PRIMARY KEY (jurnalsaldo_id),
	CONSTRAINT "fk$act$jurnalsaldo$coa_id" FOREIGN KEY (coa_id) REFERENCES act.coa(coa_id),
	CONSTRAINT "fk$act$jurnalsaldo$curr_id" FOREIGN KEY (curr_id) REFERENCES ent.curr(curr_id),
	CONSTRAINT "fk$act$jurnalsaldo$dept_id" FOREIGN KEY (dept_id) REFERENCES ent.dept(dept_id),
	CONSTRAINT "fk$act$jurnalsaldo$jurnal_id" FOREIGN KEY (jurnal_id) REFERENCES act.jurnal(jurnal_id),
	CONSTRAINT "fk$act$jurnalsaldo$jurnaldetil_id" FOREIGN KEY (jurnaldetil_id) REFERENCES act.jurnaldetil(jurnaldetil_id),
	CONSTRAINT "fk$act$jurnalsaldo$partner_id" FOREIGN KEY (partner_id) REFERENCES ent.partner(partner_id),
	CONSTRAINT "fk$act$jurnalsaldo$periode_id" FOREIGN KEY (periode_id) REFERENCES act.periode(periode_id),
	CONSTRAINT "fk$act$jurnalsaldo$project_id" FOREIGN KEY (project_id) REFERENCES prj.project(project_id),
	CONSTRAINT "fk$act$jurnalsaldo$site_id" FOREIGN KEY (site_id) REFERENCES ent.site(site_id),
	CONSTRAINT "fk$act$jurnalsaldo$unit_id" FOREIGN KEY (unit_id) REFERENCES ent.unit(unit_id)
);



CREATE INDEX "idx_fk$act$jurnalsaldo$coa_id" ON act.jurnalsaldo USING btree (coa_id);
CREATE INDEX "idx_fk$act$jurnalsaldo$curr_id" ON act.jurnalsaldo USING btree (curr_id);
CREATE INDEX "idx_fk$act$jurnalsaldo$dept_id" ON act.jurnalsaldo USING btree (dept_id);
CREATE INDEX "idx_fk$act$jurnalsaldo$jurnal_id" ON act.jurnalsaldo USING btree (jurnal_id);
CREATE INDEX "idx_fk$act$jurnalsaldo$partner_id" ON act.jurnalsaldo USING btree (partner_id);
CREATE INDEX "idx_fk$act$jurnalsaldo$periode_id" ON act.jurnalsaldo USING btree (periode_id);
CREATE INDEX "idx_fk$act$jurnalsaldo$project_id" ON act.jurnalsaldo USING btree (project_id);
CREATE INDEX "idx_fk$act$jurnalsaldo$site_id" ON act.jurnalsaldo USING btree (site_id);
CREATE INDEX "idx_fk$act$jurnalsaldo$unit_id" ON act.jurnalsaldo USING btree (unit_id);

